### ISSUE TITLE
How can I upload my app to the store?

### ISSUE THREAD

**Issue by jdev082** [Electron-Store/electron-app-store#15]
I have a few electron apps and would wish to upload them.

**Comment by jdev082** [comment]
The software I wish to upload


I use diffs in my posts to make colors.
```diff
- Catalyst (Deprecated), Windows/MacOS/Linux
+ SearchOcean App, No built binaries
+ WindEditor App, No built binaries
```

I make Electron software all the time, having it downloadable easy from a cross platform app store is amazing!

**Comment by jdev082** [comment]
I see in your roadmap
"Developer Portal to submit Apps!"

Is there anyway to get it uploaded before the feature is implemented?

**Comment by MystPi** [comment]
See #8.

**Comment by jdev082** [comment]
@MystPi oh...

**Comment by jdev082** [comment]
@MystPi little to no documentation on it tho

**Comment by jdev082** [comment]
oh i just make a PR in a repo, k

**Comment by isworking** [comment]
@JaydenDev @MystPi Our Developer portal is currently under development so it's not possible to submit apps directly as of now. The existing process of submitting PR takes too long. When the Developer Portal will be ready, we'll let you know!

**Comment by jdev082** [comment]
Ok
