### ISSUE TITLE
[BUG]a problem can't use in China

### ISSUE THREAD

**Issue by gghh2007** [Electron-Store/electron-app-store#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Build [e.g. AppImage, Snap]
 - Version [e.g. 0.0.2]

**Additional context**

**Comment by isworking** [comment]
@gghh2007 There is an issue with the old API for that is not working. I made a new and completely rewritten API and now I'm working on Electron App Store's completely rewritten version for using the new API.
